"""23213213

Revision ID: 215edb1c3cf9
Revises: d1030f5ca126
Create Date: 2025-06-10 09:51:50.663458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215edb1c3cf9'
down_revision: Union[str, None] = 'd1030f5ca126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('models', sa.Column('name_en', sa.String(length=100), nullable=False))
    op.add_column('models', sa.Column('description_en', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'description_en')
    op.drop_column('models', 'name_en')
    op.drop_column('models', 'age')
    # ### end Alembic commands ###
