"""23213213mk

Revision ID: 4935869facc4
Revises: 215edb1c3cf9
Create Date: 2025-06-10 09:56:29.751924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4935869facc4'
down_revision: Union[str, None] = '215edb1c3cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('place_en', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'place_en')
    # ### end Alembic commands ###
