"""23

Revision ID: d1030f5ca126
Revises: d209d10d94b2
Create Date: 2025-06-09 14:46:56.929955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1030f5ca126'
down_revision: Union[str, None] = 'd209d10d94b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitemanagers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('global_telegram', sa.String(), nullable=True),
    sa.Column('global_whatsapp', sa.String(), nullable=True),
    sa.Column('global_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitemanagers')
    # ### end Alembic commands ###
